### ISSUE TITLE
MD WIDGETS: Adjust the maximum string length of the label for radio buttons and checkboxes that can be displayed in a single line

### ISSUE THREAD

**Issue by tonypioneer** [anusii/markdown_widget_builder#43]
## Description

Currently, the label text for radio buttons and checkboxes will be automatically wrapped into multiple lines if it exceeds a certain number of characters. The number of characters that can fit in a single line needs to be increased.

<img width="396" alt="image" src="https://github.com/user-attachments/assets/5b97b4c7-4be5-4ea2-a7c0-8a878c8b869b">

**Comment by tonypioneer** [comment]
![image](https://github.com/user-attachments/assets/825b6756-90df-4b3d-8708-530efd87775c)

**Comment by gjwgit** [comment]
Is it possible to align the radio button icon (the circle) to the first line rather than centering it?

![image](https://github.com/user-attachments/assets/bb0ef190-5516-4100-bd26-bf453cb83dc7)
![image](https://github.com/user-attachments/assets/ee61d613-5351-4ee2-9213-e7d975582c5f)

Also, could you add a small space between the question and the first option to improve the layout.

![Screenshot From 2024-12-03 06-55-36](https://github.com/user-attachments/assets/9e4fe98e-d3ae-43c0-a3b7-177bfd53b225)

**Comment by tonypioneer** [comment]
Hi @gjwgit, I adjusted the code, and align the radio button icon to the first line. A small space has also been added between the question and the first option to improve the layout.
![image](https://github.com/user-attachments/assets/8094d38a-f052-4d00-8cae-dc1083ac8802)
